# Test
stages:
  - build
  - test
  - cleanup

build:
  stage: build
  script:
    - vagrant up
  when: always

test:
  stage: test
  script:
    - npm install
    - npm install -g grunt
    - grunt tests

cleanup:
  stage: cleanup
  script:
    - vagrant destroy -f
  when: always
